# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
email: "matt@arandomdeveloper.com"
title: "Willow Pics"
subtitle: "I like to create! Here are some of my pictures! Check them out!"
author: "Matthew Willard"
header:
 title: "Willow Pics"
 subtitle: "by Matthew (Willow) Willard"
footer:
 name: "Hello!"
 bio: "I make things and take pictures!"
 github: "Site base from <a href=\"https://github.com/ramswaroop/photography\">here!</a>"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/matthewwwillard"
  github: "https://www.github.com/matthewwwillard"
