# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
email: "matt@arandomdeveloper.com"
title: "Signing Pictures!"
subtitle: "Pictures from our marriage signing!"
author: "The Willards"
header:
 title: "Signing Pictures"
 subtitle: "by The Willards"
footer:
 name: "Hello!"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  twitter: ""
  github: ""
